### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Poussinou**
Hi,

This small PR adds a button to get your app on F-Droid. You can later add a button for Google Play the same way :
`[Get it on Google Play]()`

You can now eventually add the [fdroid](https://github.com/topics/fdroid) and/or [f-droid](https://github.com/topics/f-droid) tags that will appear on the right side of the repo.

### CODE REVIEW

**Comment by fps** [comment]
Cool! Thanks!

**Comment by fps** [comment]
Hi, I am not familiar with the tags you are talking about.. Are these setup in the repository settings somewhere?

**Comment by Poussinou** [comment]
> Hi, I am not familiar with the tags you are talking about.. Are these setup in the repository settings somewhere?

You can find some help [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics). It's far from being obligatory, just a way for people to discover your repo.

**Comment by fps** [comment]
Thanks for the info!

**Pull request merged**
